### ISSUE TITLE
Non-mercator projection example has mixed content error

### ISSUE THREAD

**Issue by tomwayson** [Esri/esri-leaflet-doc#107]
When accessing via HTTPS it shows an empty map:

https://esri.github.io/esri-leaflet/examples/non-mercator-projection.html

Works via HTTP:

http://esri.github.io/esri-leaflet/examples/non-mercator-projection.html

Looks like that service [is available over HTTPS](https://sampleserver6.arcgisonline.com/arcgis/rest/services/WorldTimeZones/MapServer/0/query?returnGeometry=true&where=POP_RANK%20%3C%203&outSr=4326&outFields=*&inSr=4326&geometry=%7B%22xmin%22%3A-32.60686906629246%2C%22ymin%22%3A-33.93260863537429%2C%22xmax%22%3A180%2C%22ymax%22%3A90%2C%22spatialReference%22%3A%7B%22wkid%22%3A4326%7D%7D&geometryType=esriGeometryEnvelope&spatialRel=esriSpatialRelIntersects&geometryPrecision=6&f=json), so it should be a minor fix.

I will PR, just putting this in as a reminder to myself.

**Comment by jgravois** [comment]
> I will PR, just putting this in as a reminder to myself.

no harm, but i needed an excuse to close #96 anyway.

**Comment by tomwayson** [comment]
I'll give that a go while I'm at it.

**Comment by tomwayson** [comment]
So the feature service is available over HTTPS, but the tile service is no longer available, so seems like we need to go w/ #96. I've included the fix for the feature service in #110.

**Comment by jgravois** [comment]
thanks for your help with this @tomwayson!
