### ISSUE TITLE
switch to node-sass and eliminate ruby dependency

### ISSUE THREAD

**Issue by tomwayson** [Esri/esri-leaflet-doc#115]
As discussed in #109

**Comment by jgravois** [comment]
> eliminate ruby dependency

i *thought* thats what i was doing in 9dbba30 when i moved us back to `grunt-sass`.

**Comment by tomwayson** [comment]
Ooops - didn't see that! nvm

**Comment by jgravois** [comment]
no worries.  it was pretty opaque of me to just start laying down commits on someone else's PR and merge them without explaining what i was doing. 

on a sunday no less.
