### ISSUE TITLE
esri enable dynamic map 

### ISSUE THREAD

**Issue by mostafakhairy** [Esri/esri-leaflet-doc#127]
i got COM error when enabling dynamic map in arc 10.5 but its working fine in 9.3 

      If (Not m_dynamicMap.DynamicMapEnabled) Then
                    m_dynamicMap.DynamicMapEnabled = True
                End If

**Comment by jgravois** [comment]
Back at 10.1 Esri stopped shipping separate .NET and Java flavors of ArcGIS Server.   My understanding is that universal python methods and our server admin API are now the preferred approach for publishing and managing services in bulk. They effectively would replace whatever .NET specific code you wrote and deployed previously. 

You can find a variety of code samples and conceptual articles related to scripting ArcGIS Server administration published in the documentation.

Scripting ArcGIS Server administration - Edit service properties
http://server.arcgis.com/en/server/latest/administer/windows/example-edit-service-properties.htm

The raw REST documentation for editing the capabilities of published services can be found below.

Server Administration API - Edit Service
http://resources.arcgis.com/en/help/arcgis-rest-api/index.html#/Edit_Service/02r3000001zp000000/

> disclaimer: you've logged your problem in a github repository that's dedicated to the online documentation for our JavaScript Leaflet plugins, so i'm *anything* but an expert.

**Comment by mostafakhairy** [comment]
my problem in local mxd ..i have map.mxd which working fine in 9.3 but i get error in 10.5 when enabling dynamic map  so i was asking if there any configuration which related to the arcmap to allow dynamic map .. or its allowing by default and the issue in other thing ..also i checked 10.5 sdk and the IdynamicMap interface still working and not  duplicated

**Comment by jgravois** [comment]
thanks for clarifying.  

since your question doesn't have anything to do with esri leaflet, please consider researching old threads on [gis.stackexchange](http://gis.stackexchange.com/), [geonet](https://geonet.esri.com/), or logging a technical support ticket.
