### ISSUE TITLE
Error loading tile layers

### ISSUE THREAD

**Issue by hhkaos** [Esri/esri-leaflet-doc#13]
I think I have found a bug:
http://esri-es.github.io/JavascriptAPI/problems/morethan1000entities/tiled_feature_leaflet.html

Cheers,
Raul

**Comment by jgravois** [comment]
is the error in behavior you're reporting the broken thumbnail links that display when leaflet attempts to fetch tiles that aren't present?

either way, this repository only contains the raw files for the esri leaflet [website](http://esri.github.io/esri-leaflet/).  can you log this issue in the project where we maintain the source code please?

https://github.com/esri/esri-leaflet

**Comment by hhkaos** [comment]
Yes John, sorry for taking so long to reply, I'm didn't see you message. BTW, I'll be at Palm Springs tomorrow :).

I just opened [the issue](https://github.com/Esri/esri-leaflet/issues/759) in the right repo.

Thanks!
