### ISSUE TITLE
Docs website high browser CPU usage

### ISSUE THREAD

**Issue by madeindata** [Esri/esri-leaflet-doc#138]
The animating map background is overloading web browsers cpu. Both current chrome and Firefox on i7 macbook start eating cpu longer the browser is on https://esri.github.io

Offending JS is likely this:
[https://github.com/Esri/esri-leaflet-doc/blob/master/src/js/script.js#L13](https://github.com/Esri/esri-leaflet-doc/blob/master/src/js/script.js#L13)
triggers constant translate3d animation.

I don't think this animation is needed for a docs site, especially considering the resource drain for a site users are likely to have open for extended periods of time as reference.

**Comment by jgravois** [comment]
i think the animation is pretty fun, but if you want to submit a PR, i'd merge it.

**Comment by madeindata** [comment]
#139
