### ISSUE TITLE
new sample: esri leaflet indoors

### ISSUE THREAD

**Issue by jgravois** [Esri/esri-leaflet-doc#142]
it'd be cool to put together a new sample that mashes up esri map/feature services with `L.indoor`

https://github.com/cbaines/leaflet-indoor

**Comment by gavinr** [comment]
It looks like this plugin [requires leaflet 0.7.x](https://github.com/cbaines/leaflet-indoor/issues/8) - since our sample pages use Leaflet v1.2.0, I think [this issue](https://github.com/cbaines/leaflet-indoor/issues/9) is a prerequisite before we can create a sample with this tool.

**Comment by jgravois** [comment]
i actually put in a `legacy: true` flag in page templates so that we could maintain the flexibility to load leaflet `1.0.3`. wouldn't be hard to extend that logic.

https://github.com/Esri/esri-leaflet-doc/blob/1d8cc8b13e501155f03b950bea8a4188c244ffb1/src/pages/examples/editing.hbs#L5

another option would be to see what would be required to bump it to be Leaflet 1.x compatible.

**Comment by gavinr** [comment]
@jgravois nice! didn't realize that was built-in. I have a demo I was playing with ... let me try it on that and see if I can get it to work.

**Comment by jgravois** [comment]
deployed. thank you!

**Comment by jwasilgeo** [comment]
@gavinr @jgravois looks like this resource is no longer available, so the demo page silently fails:

https://www25.swfwmd.state.fl.us/arcgis/rest/services/Internal/FacilitiesSearch/MapServer/0
