### ISSUE TITLE
Error when trying to edit

### ISSUE THREAD

**Issue by stevehmig** [Esri/esri-leaflet-doc#15]
When clicking on a feature to edit, I get this error:
Uncaught TypeError: Cannot read property 'lat' of null

I get this error both on the sample page (https://esri.github.io/esri-leaflet/examples/editing.html), and in my own testing.

**Comment by jgravois** [comment]
thanks for the report.  the version of the draw plugin we're using is compatible with leaflet `1.0.0-beta.2`.  we'll be rewriting this sample soon.

Esri/esri-leaflet#684
