### ISSUE TITLE
name parameter L.esri.dynamicLayer

### ISSUE THREAD

**Issue by kcarrier** [Esri/esri-leaflet-doc#152]
Is it possible to specify a name for a layer in the L.esri.dynamicLayer

I looked over the documentation and did not see any parameters which make this possible

https://esri.github.io/esri-leaflet/api-reference/layers/dynamic-map-layer.html

I would like to override the default name of the service.

Any help would be appreciated.

**Comment by jgravois** [comment]
> Is it possible to specify a name for a layer

can you clarify exactly what you mean and how the option/capability would be helpful to you? I don't quite understand what you mean by "override the default name of the service" either.

**Comment by kcarrier** [comment]
I am used to the JSAPI from Esri where you have more parameters/options.

I was hoping to name the layer for use in a layer control. 

I found a workaround but was just curious why you could not name the layer within dynamicLayer or why that parameter option was not exposed. Again I am new to the Leaflet world just trying to learn.

```
	var map = L.map('map');
	
	// new constructor syntax at 2.0.0
	var watermainbreaks = L.esri.Heat.featureLayer({
		url: 'http://maps4.hamilton-city.org/arcgis/rest/services/WaterMainBreaks/MapServer/0',
		radius: 60
	}).addTo(map);

	var sanitarylyrs = L.esri.dynamicMapLayer({
		url: "http://maps3.hamilton-city.org/arcgis/rest/services/FlexAppOperationalLayerSanitary15/MapServer"
	});
	
	var waterlyrs = L.esri.dynamicMapLayer({
		url: "http://maps2.hamilton-city.org/arcgis/rest/services/FlexAppOperationalLayerWater15/MapServer"
	}).addTo(map);
	
	var aerial2016 = L.esri.tiledMapLayer({
		url: "http://maps1.hamilton-city.org/arcgis/rest/services/Aerial2016/MapServer",
		maxZoom: 21
	}).addTo(map);
	
	var baseLayers = {
      "Aerial 2016": aerial2016
	};
	
	  var overlays = {
      "Water Main Breaks": watermainbreaks,
	  "Water": waterlyrs,
	  "Sanitary": sanitarylyrs
	};
	
	//var esriLeafletLegend = require("esri-leaflet-legend");
	L.control.layers(baseLayers, overlays).addTo(map);
	//L.esri.legendControl(waterlyrs).addTo(map);
```

**Comment by jgravois** [comment]
```js
var overlays = {
    "Water Main Breaks": watermainbreaks,
    "Water": waterlyrs,
    "Sanitary": sanitarylyrs
};
```
your opportunity to control display names in Leaflet's layer control are the strings that correspond with each layer in the JSON object literals you pass to it's constructor.

**Comment by kcarrier** [comment]
Right i figured it out but from my past i thought it could be controlled at
the dynamicLayer parameter.

**Comment by jgravois** [comment]
okay. sounds like we're all good here then.  

if you have more questions in the future, on this or any other topic, _please_ don't be shy.
