### ISSUE TITLE
make nav header links collapsable on mobile phones

### ISSUE THREAD

**Issue by jgravois** [Esri/esri-leaflet-doc#163]

**Comment by gavinr** [comment]
@jgravois are you thinking something like this?
    ![image](https://user-images.githubusercontent.com/209355/31951055-ac01ee56-b8a2-11e7-89a9-d43ce4eaceac.png)
    ![image](https://user-images.githubusercontent.com/209355/31951257-365f9c38-b8a3-11e7-87e1-0d0c079cb83d.png)

I'm also noticing that the [homepage gets cut off](https://user-images.githubusercontent.com/209355/31949612-61babe84-b89f-11e7-81e6-b2b70f07dff7.jpg) on most mobile resolutions, so maybe we could also fix that as part of this item?

**Comment by jgravois** [comment]
that'd be awesome.
