### ISSUE TITLE
Update "searchText" to "text"

### ISSUE THREAD

**Issue by matt-e-king** [Esri/esri-leaflet-doc#165]
Creating an issue on correct repo, reference to original issue:
https://github.com/Esri/esri-leaflet/issues/1024

**Comment by matt-e-king** [comment]
https://github.com/Esri/esri-leaflet-doc/pull/166

**Comment by jgravois** [comment]
you are correct that `searchText` is a typo. its the param name we pass to the REST service, but not the method name.

extreme bonus points if you could send a pull request with the fix. the markdown with the page content is [`dynamic-map-layer.md`](https://github.com/Esri/esri-leaflet-doc/blob/4a2734ae86918fb1266ba61c0cbc0513d3aa52ff/src/pages/api-reference/layers/dynamic-map-layer.md)
