### ISSUE TITLE
doc new distinct() method on Tasks.Query

### ISSUE THREAD

**Issue by jgravois** [Esri/esri-leaflet-doc#167]
see https://github.com/Esri/esri-leaflet/pull/1028 for more info

cc/ @joelondon

**Comment by gavinr** [comment]
Was this covered in https://github.com/Esri/esri-leaflet-doc/commit/9edc84492e4288f9e4cbf0baabdeebb99ec84255#diff-6fb322b1d8efd21b6978e94d9ac443d3R155?

**Comment by jgravois** [comment]
yes! good catch.

http://esri.github.io/esri-leaflet/api-reference/tasks/query.html
