### ISSUE TITLE
Update examples to leaflet 1.3.0

### ISSUE THREAD

**Issue by gavinr** [Esri/esri-leaflet-doc#170]
Leaflet 1.3.0 was just released: 

- https://github.com/Leaflet/Leaflet/releases/tag/v1.3.0
- https://unpkg.com/leaflet@1.3.0/dist/leaflet.js

**Comment by jgravois** [comment]
closed via https://github.com/Esri/esri-leaflet-doc/commit/96a6de26a0efcf2a8672ff16cb67d195b2244319
