### ISSUE TITLE
Clean up Tutorials

### ISSUE THREAD

**Issue by gavinr** [Esri/esri-leaflet-doc#193]
1. [ ] Both [migration](http://esri.github.io/esri-leaflet/tutorials/migrating-1-to-2.html) [guides](http://esri.github.io/esri-leaflet/tutorials/migrating-release-candidates-to-1.html) say "coming soon." V2 came out 2-3 years ago - safe to just remove these "migration guide" placeholders?
2. [ ] All the pages under `Module Systems` say "coming soon" - are these four (`Browserify`, `Webpack`, `JSPM`, `RequireJS`) still relevant?
3. [ ] [Discovering content](http://esri.github.io/esri-leaflet/tutorials/discovering-content.html) - currently says coming soon. What was meant to be here?

**Comment by pmacMaps** [comment]
Some of the tutorials could also use an updating of the versions of Leaflet and Esri Leaflet they reference.

**Comment by jgravois** [comment]
I'm definitely on board with removing all the 'placeholder' tutorials.
