### ISSUE TITLE
I sent proposed edits to the readme.md as a PR. Is that okay?

### ISSUE THREAD

**Issue by perchslayer** [Esri/esri-leaflet-doc#199]
On line 135 of the readme:

1) Stackexchage should be StackExchange (capital "E")

2) I suggest linking "GeoNet" to the ESRI Community portal URL where it is found @ https://community.esri.com/

**Comment by jgravois** [comment]
👍

https://github.com/perchslayer/esri-leaflet/pull/1#pullrequestreview-166792703

**Comment by jgravois** [comment]
closed via https://github.com/Esri/esri-leaflet/commit/0489576eaf245ad52e298bbd8fa461192a1226dc
