### ISSUE TITLE
indoor feature service no longer available

### ISSUE THREAD

**Issue by jgravois** [Esri/esri-leaflet-doc#202]
https://www25.swfwmd.state.fl.us/arcgis/rest/services/Internal/FacilitiesSearch/MapServer/0 404s

_Originally posted by @jwasilgeo in https://github.com/Esri/esri-leaflet-doc/issues/142#issuecomment-444992737_

**Comment by gavinr** [comment]
Thanks for finding this @jwasilgeo. I remember when I was creating this demo I could not find any good demo data on any sampleservers ... I'll just publish some simple sample data in a hosted feature service and switch it over to that.
