### ISSUE TITLE
Cluster examples broken

### ISSUE THREAD

**Issue by gavinr** [Esri/esri-leaflet-doc#212]
Neither of these examples seem to be working:

- https://esri.github.io/esri-leaflet/examples/clustering-feature-layers.html
- https://esri.github.io/esri-leaflet/examples/styling-clusters.html

I'm getting an error in the console: `TypeError: L.esri.Cluster is undefined`

**Comment by jgravois** [comment]
this is because of https://github.com/unpkg/unpkg.com/issues/156

if you could bump the urls to call out the [explicit filename](https://unpkg.com/esri-leaflet-cluster@2.0.0/dist/esri-leaflet-cluster.js) it'd be much appreciated.
