### ISSUE TITLE
Cluster example broken

### ISSUE THREAD

**Issue by gavinr** [Esri/esri-leaflet-doc#226]
Nothing showing up on the map (other than the basemap): 

- [x] https://esri.github.io/esri-leaflet/examples/clustering-feature-layers.html
- [ ] https://esri.github.io/esri-leaflet/examples/styling-clusters.html

... looks like the demo layer we're using has been secured: https://services.arcgis.com/rOo16HdIMeOBI4Mb/arcgis/rest/services/Trimet_Transit_Stops/FeatureServer/0

We should find a new public service (perhaps on one of the esri sampleservers?) to use for the demo.

**Comment by jgravois** [comment]
@patrickarlt the TriMet service above is no longer public. was that a mistake?

**Comment by jgravois** [comment]
same problem with this one: http://esri.github.io/esri-leaflet/examples/getting-service-metadata.html

**Comment by pmacMaps** [comment]
If new services are needed for these examples, I take on the assignment.  But I'll wait until @patrickarlt is able to reply regarding the status of the existing services.

**Comment by pmacMaps** [comment]
I think this specific issue can be closed, as the example at `https://esri.github.io/esri-leaflet/examples/styling-clusters.html` was fixed in #231.
