### ISSUE TITLE
"Points as a heatmap" sample broken (service set to private)

### ISSUE THREAD

**Issue by xigolle** [Esri/esri-leaflet-doc#227]
* Browser and version:

Chrome Version 75.0.3770.100

* Version of Leaflet (`L.version`):

* Version of esri Leaflet (`L.esri.VERSION`):

1.0.4, 2.0.3, `master`?

Steps to reproduce the error:

1. Go to: http://esri.github.io/esri-leaflet/examples/visualize-points-as-a-heatmap.html

What happens is [X].

No heatmaps are shown

I was expecting [Y].
An heatmap

(if possible, create a [jsbin](http://jsbin.com/dagilag/edit?html,output) that demonstrates the problem)

* Optional: I'm *not* using the [CDN](http://www.jsdelivr.com/projects/leaflet.esri), I'm loading/bundling the library using:

[webpack](https://webpack.github.io/), [browserify](http://browserify.org/), [RequireJS](http://requirejs.org/)?

There are a lot of these demo's/examples that are not working. 
Is there a reason for this (not supported anymore?).
If you want a complete list of all the demo's that are not working I can provide that.

**Comment by gavinr** [comment]
@xigolle thanks for the report. It seems like this one is not working due to the service it's using (https://services.arcgis.com/rOo16HdIMeOBI4Mb/ArcGIS/rest/services/Graffiti_Reports/FeatureServer/0) not being shared anymore. This is similar to the issue #226 that we're working though over there.

**Comment by gavinr** [comment]
http://esri.github.io/esri-leaflet/examples/visualize-points-as-a-heatmap.html now working again thanks to #228 ...

but https://esri.github.io/esri-leaflet/examples/styling-heatmaps.html still not working so i'll leave this item open for now.

**Comment by gavinr** [comment]
@xigolle those samples are now fixed. Sorry about the confusion.

**Comment by xigolle** [comment]
Thanks for fixing it!
