### ISSUE TITLE
Plugins Page - Split up

### ISSUE THREAD

**Issue by gavinr** [Esri/esri-leaflet-doc#234]
Per the [recent announcement](https://github.com/Esri/esri-leaflet/issues/1160#issue-468189876), this issue is to divide up the [plugins page](https://esri.github.io/esri-leaflet/plugins/) into official plugins and plugins from community members to be clearer about what we are supporting.

To accomplish this, we need to figure out two things:
1. Which plugins are which?
2. Design-wise, how will we split up the page. One simple option I'll just throw out there might be to add headers:
    ![image](https://user-images.githubusercontent.com/209355/62050711-70cbcc00-b1d7-11e9-88da-8aa88560e202.png)

**Comment by pmacMaps** [comment]
I think simpler is better.  And I like your example.  It might also be nice to provide a brief (1-2 sentence) description or definition for what "Official" and "Community" means.

I would also like to see [Esri Leaflet Legend](https://github.com/w8r/esri-leaflet-legend) added under the "Community" group.

**Comment by jgravois** [comment]
### Official (and need maintainers)
* Geocoder
* Renderers
* Clustered Feature Layer
* Heatmap Feature Layer
* shapeMarkers
### Community
* WebMap
* Stream Feature Layer
* Dynamic Map Layer (advanced)
* Canvas Flowmap Layer
* Legend
* Geoprocessing*
* Related Records*
* Leaflet Routing Machine*

*I'm happy to transfer the plugins under my own account to the Esri organization (as we did with [react-arcgis](https://github.com/Esri/react-arcgis) when we lost @nicksenger), but there's no need to do that unless we can actually identify folks interested in taking over maintenance of them.

###  Deprecated (I'd recommend just removing it from the list and API reference)
* Vector Tiles
