### ISSUE TITLE
Some examples are not working on http connections

### ISSUE THREAD

**Issue by BrunoCaimar** [Esri/esri-leaflet-doc#24]
Some examples are not working on http connections due to the service that they are using are not accepting http connections anymore. 

Some of the examples that are not working: Simple FeatureLayer, Custom popups, Querying features, etc. 

I'll try to send a pull request to fix it soon. 

![bad_request_on_leaflet_example](https://cloud.githubusercontent.com/assets/44867/14540761/1b9f76b4-025d-11e6-8b93-f4e747a1c823.png)

**Comment by jgravois** [comment]
deployed your fix.  thanks again.
