### ISSUE TITLE
Add Linting

### ISSUE THREAD

**Issue by jwasilgeo** [Esri/esri-leaflet-doc#241]
[`esri-leaflet`](https://github.com/Esri/esri-leaflet/) is wired up with `semistandard` linting ([here](https://github.com/Esri/esri-leaflet/blob/master/package.json#L81), [here](https://github.com/Esri/esri-leaflet/blob/master/package.json#L93)), but I haven't yet identified that this repo enforces  linting via an npm script or a Grunt task.

Since we're already using Grunt here, does anyone have a preference on the latest and greatest in that ecosystem?  I admittedly haven't been staying up to date with that lately.

**Comment by jwasilgeo** [comment]
I dug a little deeper into the 🐇 🕳  and found that `grunt-contrib-jshint` is already in the npm packages `devDependencies`, but seems to be unused yet by Grunt.

https://github.com/Esri/esri-leaflet-doc/blob/master/package.json#L26

I'll attempt to wire it up into our Grunt tasks.

**Comment by jwasilgeo** [comment]
Work is underway in branch [`241-add-linting`](https://github.com/Esri/esri-leaflet-doc/tree/241-add-linting).

- [x] wired up eslint with grunt watch
- [ ] verify if eslint needs to be wired up anywhere else in other grunt tasks (build/deploy tasks?)
- [x] eslint applied to src/pages/examples `.hbs` files
- [x] eslint applied to src/pages/tutorials `.md` files
- [ ] there are some eslint errors we may want to ignore in the src/pages/tutorials `.md` files
- [x] eslint applied to high-level /src/helpers and /src/js `.js` files
- [ ] eslint applied to src/pages/api-reference `.md` files

**Comment by gavinr** [comment]
@jwasilgeo re:

> find out why the grunt docs:build task calls 'sass' twice; can we insert 'eslint' anywhere here?

I think this is due to `sass` being listed twice [here](https://github.com/Esri/esri-leaflet-doc/blob/dccf815bc89f1ad7dd39ef9e990eefbed633527b/Gruntfile.js#L132). @jgravois do you happen to know/remember if this was done on purpose or perhaps it's simply a mistaken duplication.

**Comment by jgravois** [comment]
> never attribute to malice what is adequately explained by john's carelessness or stupidity on john's part. 😇 - [Hanlon's Razor](https://en.wikipedia.org/wiki/Hanlon%27s_razor) (amended)

**Comment by jwasilgeo** [comment]
1. @jgravois 😆😆; @gavinr shall we strike one of those `sass` listings and figure out where to add in `eslint` without its own error reporting forcing an early exit during the given grunt task(s)?

2. Perfect, thanks again for that @gavinr.  I'll check off those items in the todo list above.

**Comment by jwasilgeo** [comment]
The more I look at it the less sure I am about which `sass` to remove on [this line](https://github.com/Esri/esri-leaflet-doc/blob/241-add-linting/Gruntfile.js#L140). @jgravois @gavinr I might just leave it alone for right now.

**Comment by jgravois** [comment]
> The more I look at it the less sure I am about which sass to remove.

I wouldn't expect it to matter which one you remove. are you seeing something weird locally?

**Comment by jwasilgeo** [comment]
Nah, I'm just tracking too many changes and subtopics in my mind and getting a little turned around.  I'll strike one and commit the change.  Thank you!

**Comment by jwasilgeo** [comment]
Closed via PR #244.
