### ISSUE TITLE
Indicate active page among sidebar choices

### ISSUE THREAD

**Issue by jwasilgeo** [Esri/esri-leaflet-doc#243]
It might be nice to indicate in the sidebar of the docs which page among its sibling choices is currently active.  Thoughts?

Here are some of the files we could consider modifying.

- `src\partials\sidebar-examples.hbs`
- `src\partials\sidebar-documentation.hbs`
- `src\partials\sidebar-tutorials.hbs`

One approach may be to look up the `<a>` that corresponds to the current url based on `href` attribute and change the font, color, etc. style attributes (or apply a css class, so on).

A simple working example to prototype this idea:

```html
<script>
  var activeLinkElement = document.querySelector(`a[href*="${window.location.pathname}"]`);

  // this color comes from the sass theme, btw, and happens to be the current color of the font
  // this border bottom is already used for :hover
  activeLinkElement.style.borderBottom = '2px solid #79BD8F';

  activeLinkElement.style.fontWeight = 'bold';
</script>
```

And here's an example of what that would look like:

![image](https://user-images.githubusercontent.com/4933392/63058370-25d9d600-beb2-11e9-8b3a-c61e2d935a4b.png)

**Comment by pmacMaps** [comment]
I'm in favor of this enhancement for all the pages with the sidebar (tutorials, api reference, and examples).  I don't have strong feelings about how to highlight the current page.

It might be nice to see a couple approaches for how to highlight the current page.  Another idea is to have the background of the link as a colored tab.

![esri-leaflet-doc-higlight-current-page-graphic](https://user-images.githubusercontent.com/12861454/63096299-9b3db900-bf3b-11e9-8ea0-84b33013cf92.PNG)
