### ISSUE TITLE
SEO: Meta Description

### ISSUE THREAD

**Issue by gavinr** [Esri/esri-leaflet-doc#249]
Right now our `<meta name="description" content="...">` tag's content is `Esri Leaflet`, which is just a duplicate of the page title.

![image](https://user-images.githubusercontent.com/209355/65772767-85a5dc80-e100-11e9-9c35-c6b375a84cca.png)

I think this should be changed to a short, 1-2 sentence summary of the project. Maybe the homepage text if nothing else:

>A lightweight set of tools for using ArcGIS services with Leaflet.

**Comment by jgravois** [comment]
that's a great idea.

feel free to just open PRs to discuss stuff like this directly if it's more convenient.
