### ISSUE TITLE
Possiblity of Two Meta Description tags

### ISSUE THREAD

**Issue by gavinr** [Esri/esri-leaflet-doc#250]
It looks like if a page has a "Description" in its `page.data`, we could have two `<meta name="description" .... >` tags on the page ([see code here](https://github.com/Esri/esri-leaflet-doc/blob/5a186bf14d6c373e08e57f20e3e3732ef0409b88/src/partials/header.hbs#L16-L20)). I don't think this is happening in practice anywhere, but we probably should not have the possibility for it to happen - could we make this an if/else instead, so only one meta description tag is ever on the page at once.

**Comment by jwasilgeo** [comment]
closed via PR #253
