### ISSUE TITLE
Integrity string on esri-leaflet-cluster

### ISSUE THREAD

**Issue by gavinr** [Esri/esri-leaflet-doc#254]
In the examples, for most plugins we have the "integrity string" included in the sample code. Example [here](https://esri.github.io/esri-leaflet/examples/geocoding-control.html):

![image](https://user-images.githubusercontent.com/209355/65971214-74750c80-e42d-11e9-8af0-1829024b1d6b.png)

... but that is not included in certain other example pages, for example with `esri-leaflet-cluster` [here](https://esri.github.io/esri-leaflet/examples/clustering-feature-layers.html) and [here](https://esri.github.io/esri-leaflet/examples/styling-clusters.html) (any others?). We should probably enable the integrity string for these ones as well for consistency.

![image](https://user-images.githubusercontent.com/209355/65971415-c027b600-e42d-11e9-8d90-1f8a0127f1fc.png)

**Comment by gavinr** [comment]
Note: a side-effect of this code update will mean that [this line](https://github.com/Esri/esri-leaflet-doc/blob/8fa92e9eb52465515ab3df586f3f19c3a2d57912/src/pages/examples/styling-clusters.hbs#L12) will be auto-generated instead of hardcoded (similar to how it works [here](https://github.com/Esri/esri-leaflet-doc/blob/8fa92e9eb52465515ab3df586f3f19c3a2d57912/src/pages/examples/geocoding-control.hbs#L5)), which is great too.

**Comment by jwasilgeo** [comment]
@gavinr we can close this either now or when the docs are regenerated and pushed to github pages, yes?
