### ISSUE TITLE
OAuth DOMException

### ISSUE THREAD

**Issue by harwelld** [Esri/esri-leaflet-doc#266]
When I use the OAuth sample provided in the examples page, the login window does not close once I sign in. It appears I am getting a token by looking at the url, but there is a DOMException being thrown and the window persists.
![ESRI-leaflet-OAuth](https://user-images.githubusercontent.com/43053356/79358564-36859480-7ef6-11ea-81a1-fe3202aa0972.PNG)

**Comment by gavinr** [comment]
Are you talking about this page
https://esri.github.io/esri-leaflet/examples/arcgis-online-auth.html
?

It seems to be working for me:
![image](https://user-images.githubusercontent.com/209355/79404892-798d4980-7f82-11ea-8672-5d624d72490a.png)

Could you tell us some more details about your setup (OS, browser, versions, etc)?

**Comment by harwelld** [comment]
Yep, that page. I'm on Chrome Version 80.0.3987.163. I tried it through the sample, tried it by copying the sample to a html file and running locally, tried clearing my browser cache, no matter what I have done I get that DOMException and the login window persists, the token never displays in the input on the map.

**Comment by gavinr** [comment]
Works fine for me with an OAuth login (in my case Okta, but should be equivalent to DueMobile)
![image](https://user-images.githubusercontent.com/209355/79412214-73a06400-7f94-11ea-9f3f-69a5d3c87dba.png)

Do you have access to another machine and/or network that you could test on? I'll also try to test in a few different environments

**Comment by jwasilgeo** [comment]
@harwelld I gave this a whirl with Firefox and Chrome and didn't see any of the described issues. Following up with @gavinr's request, can you provide more info and try another computer or network (home vs office etc)?

**Comment by jwasilgeo** [comment]
Closing for now due to inactivity but please feel free to reopen if you see the issue again and can provide some more details and perhaps try on other machines/networks.
