### ISSUE TITLE
Reverse Geocoding ist Undefined

### ISSUE THREAD

**Issue by Dsabillon** [Esri/esri-leaflet-doc#272]
When i use a reverse geocoding the console throw me :
```
app.js:22 Uncaught TypeError: Cannot read property 'Geocoding' of undefined
    at HTMLInputElement.buscarDireccion (app.js:22)
```

This is my Code of app.js.

```
import { OpenStreetMapProvider } from "leaflet-geosearch";

const lat = 20.5;
const lng = -103.5;
const map = L.map("mapid").setView([lat, lng], 15);

let markers = new L.FeatureGroup().addTo(map);
let marker;

document.addEventListener("DOMContentLoaded", () => {
  L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", {
    attribution:
      '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
  }).addTo(map);

  const buscador = document.querySelector("#formbuscador");
  buscador.addEventListener("input", buscarDireccion);
});

function buscarDireccion(e) {
  if (e.target.value.length > 8) {
    //si existe un pin anterior, limpiarlo
    markers.clearLayers();

    //Utilizar el provider y GeoCoder
    var geocodeService = L.esri.Geocoding.geocodeService();
    const provider = new OpenStreetMapProvider();
    provider.search({ query: e.target.value }).then((resultado) => {
      geocodeService
        .reverse()
        .latlng(resultado[0].bounds[0], 15)
        .run(function (error, result) {
          console.log(result);

          //mostrar el mapa
          map.setView(resultado[0].bounds[0], 15);

          marker = new L.marker(resultado[0].bounds[0], {
            draggable: true,
            autoPan: true,
          })
            .addTo(map)
            .bindPopup(resultado[0].label)
            .openPopup();

          //detectar movimineto del marker
          marker.on("moveend", function (e) {
            marker = e.target;
            const posicion = marker.getLatLng();
            map.panTo(new L.LatLng(posicion.lat, posicion.lng));
          });

          //asignar al contenedor
          markers.addLayer(marker);
        });
    });
  }
}
```

**Comment by jwasilgeo** [comment]
Hi @Dsabillon, the available providers you can use with [esri-leaflet-geocoder](https://github.com/Esri/esri-leaflet-geocoder) are listed here:

<https://esri.github.io/esri-leaflet/api-reference/controls/geosearch.html#available-providers>

Unfortunately, one cannot use providers from other, unrelated Leaflet plugins, such as "leaflet-geosearch".

**Comment by jgravois** [comment]
the use of 'leaflet-geosearch' is actually irrelevant here. they'd hit the error when reverse geocoding any hardcoded string.

see https://github.com/Esri/esri-leaflet-geocoder/issues/219 and many others.

**Comment by jwasilgeo** [comment]
Thanks for helping out, @jgravois. That's what I get for skimming code without enough coffee.

I am looking more closely at the `app.js ` code snippet; are you also saying at this line
`var geocodeService = L.esri.Geocoding.geocodeService();`
there is an import/namespace technicality going on here based on the issue you reference?

What else is at play here?

@Dsabillon, I see that is the `.reverse()` method you use wraps the ReverseGeocode task. ([`L.esri.Geocoding.ReverseGeocode`](https://esri.github.io/esri-leaflet/api-reference/tasks/reverse-geocode.html)) I'm not sure that it matters at all, but the `latlng` method only takes 1 argument for the coordinates.
