### ISSUE TITLE
"Zoom to all features" example page not working

### ISSUE THREAD

**Issue by gavinr** [Esri/esri-leaflet-doc#275]
https://esri.github.io/esri-leaflet/examples/zooming-to-all-features-1.html

Due to the fact that the layer being used:
https://public.gis.lacounty.gov/public/rest/services/LACounty_Dynamic/LMS_Data_Public/MapServer/18

is not working:
![image](https://user-images.githubusercontent.com/209355/87055814-59bd9880-c1f4-11ea-9f1d-ea674f423d7c.png)

Should we switch this to a more consistent layer?

**Comment by jgravois** [comment]
definitely.

**Comment by jwasilgeo** [comment]
Thanks again @pmacMaps. All good now on the live docs site. 😺 https://esri.github.io/esri-leaflet/examples/zooming-to-all-features-1.html
