### ISSUE TITLE
Local doc site point to local esri-leaflet.js

### ISSUE THREAD

**Issue by gavinr** [Esri/esri-leaflet-doc#279]
Sometimes as part of [smoke-testing](https://en.wikipedia.org/wiki/Smoke_testing_(software)) it's a good step to run all the sample pages in the documentation against a new build that of `esri-leaflet.js` that you have locally. I haven't found a great way to do this - is there a method to do this that I'm missing?

If not, it would be nice if we could modify the `esri-leaflet-doc` code so that it's easy to point your local build of the documentation pages temporarily to use a local `esri-leaflet.js` file.

**Comment by pmacMaps** [comment]
I would add that it would be nice to test a local build of doc pages against all of the official esri-leaflet plugins.  I ran into this issue with a recent update I made to the geocoders plugin.

It looks like this functionality may already exist:
- `localSource` setting in [devSiteData.json](https://github.com/Esri/esri-leaflet-doc/blob/master/data/devSiteData.json#L3)
- If `localSource` is true, then it's expecting the individual to have loaded certain files. See [header.hbs](https://github.com/Esri/esri-leaflet-doc/blob/master/src/partials/header.hbs#L41)

**Comment by jgravois** [comment]
@pmacMaps is right. there's definitely room for improvement there though.

**Comment by gavinr** [comment]
@jgravois looks like by default it looks at `/js/linked/leaflet-dist/...` ... how does that folder get created? Or is that a manually created symlink or something?

**Comment by jgravois** [comment]
> is that a manually created symlink

exactly. it's just a hacky solution I came up with before I knew about [`npm link`](https://docs.npmjs.com/cli/link). anything you feel like doing to improve the DX would be appreciated.
