### ISSUE TITLE
Demo server requires token

### ISSUE THREAD

**Issue by ahocevar** [Esri/esri-leaflet-doc#287]
The [editable emample](http://leaflet.marsgis.cn/forleaflet/plugins/esri-leaflet/examples/editable.html) no longer works, because the server refuses to respond with data.

The first request that the example sends is
        https://services.arcgis.com/rOo16HdIMeOBI4Mb/arcgis/rest/services/PDX_Pedestrian_Districts/FeatureServer/0/?f=json

The response is
```json
{
    "error": {
        "code": 499,
        "message": "Token Required",
        "messageCode": "SB_0005",
        "details": [
            "Token Required"
        ]
    }
}

**Comment by pmacMaps** [comment]
That link does not appear to be from the "official" documentation site.  I tested on the editing examples, and didn't experience any issues in Chrome.

Check out these links:
- [Editing #1](https://esri.github.io/esri-leaflet/examples/simple-editing.html)
- [Editing #2](https://esri.github.io/esri-leaflet/examples/editable.html)

**Comment by jwasilgeo** [comment]
Thanks for clarifying, @pmacMaps

**Comment by ahocevar** [comment]
Nice! Thanks a lot and sorry for the noise.

**Comment by jwasilgeo** [comment]
No worries whatsoever, glad we got it figured out!
