### ISSUE TITLE
Add documentation for web mercator and esri-leaflet-vector L.esri.Vector.vectorTileLayer

### ISSUE THREAD

**Issue by jwasilgeo** [Esri/esri-leaflet-doc#310]
Wait until the next version of esri-leaflet-vector is released (after current 3.0.1)

https://github.com/Esri/esri-leaflet-vector/blob/master/CHANGELOG.md#upcoming-changes

**Comment by jwasilgeo** [comment]
https://github.com/Esri/esri-leaflet-vector/issues/86

https://github.com/Esri/esri-leaflet-vector/issues/94

**Comment by jwasilgeo** [comment]
This API docs page does a nice job explaining a similar requirement for another layer type: https://esri.github.io/esri-leaflet/api-reference/layers/tiled-map-layer.html

**Comment by pmacMaps** [comment]
Could the same text used on the Tile Map Layer be used on the [Vector Tile Layer](https://esri.github.io/esri-leaflet/api-reference/layers/vector-layer.html) page?

**Comment by jwasilgeo** [comment]
Patrick, sure thing, that's what I was thinking too. PRs welcome. 😸
