### ISSUE TITLE
Typo in L.esri.TiledMapLayer

### ISSUE THREAD

**Issue by jmitz** [Esri/esri-leaflet-doc#34]
Third paragraph says:

> Is you have Feature Services published in ArcGIS Online you can create a static set of tiles using your Feature Service. You can find details about that process in the ArcGIS Online Help

Probably intended:

**If** you have Feature Services published in ArcGIS Online you can create a static set of tiles using your Feature Service. You can find details about that process in the ArcGIS Online Help

**Comment by jgravois** [comment]
fixed in 6958fae.  thanks for the report.  the problem will be fixed in the live site next time we push an update to the `gh-pages` branch.
