### ISSUE TITLE
create a 'make your first map' tutorial

### ISSUE THREAD

**Issue by jgravois** [Esri/esri-leaflet-doc#44]
more info Esri/esri-leaflet#688

**Comment by pmacMaps** [comment]
I'm still interested in helping, just not sure when I'll have time.

**Comment by jgravois** [comment]
i'm not complaining.  i haven't gotten around to it yet either. 😆 

http://esri.github.io/esri-leaflet/tutorials/

if you ever *do* have a chance to sketch something up, even if its really rough, getting the ball rolling would be *extremely* helpful.

**Comment by pmacMaps** [comment]
I'm going to work on getting this basic tutorial finished by the end of August.  What were you hoping would be covered in this tutorial?

I was thinking of the following:

1.  Add basemap from AGOL
2.  Add a feature service
     a. create a pop-up
     b. custom style or just use renderer's plugin
3.  Add a map service
     a. create a pop-up
4.  Create a layer control with AGOL basemaps and two overlay services

I'm assuming I'll also need to cover constructing the L.map as well (and HTML/CSS related to that).

Is this what you were thinking?

**Comment by jgravois** [comment]
all that sounds great! if you're going to try and cover that many topics, you might even consider organizing things into several individual concise tutorials.

### Getting started
- [ ] add a basemap from AGOL. 

> discuss the HTML/CSS and explain that esri-leaflet is a plugin that extends what Leaflet provides all on its own.

### Working with feature layers
- [ ] add a feature service and defining a popup.  afterward, add the renderers plugin

### Using layer controls
- [ ] use Leaflet's layer control to create a toggle for two different basemaps and checkbox to turn a dynamicMapLayer on and off

### ???

i expect this will be more digestible for folks, and hopefully it will make the project less overwhelming if we chip away at them one at a time.

**Comment by pmacMaps** [comment]
I like that!  My only comment is maybe we also have a separate tutorial for working with dynamicMapLayer.

We could then use a feature layer and dynamicMapLayer on the control?

**Comment by jgravois** [comment]
> My only comment is maybe we also have a separate tutorial for working with dynamicMapLayer.

you're the one volunteering, so any tutorial you think would be helpful is fine by me.

> what version of Leaflet/ESRI-Leaflet should these be?

my instinct is to just write them using Leaflet `1.0.0-rc.2` and Esri Leaflet `2.0.1`, but if you'd like to write them for `0.7.x` it'd be a breeze to update them later.

**Comment by pmacMaps** [comment]
My experience has been with the 0.7.x version of Leaflet, so I'll go with that.  We can update them later, as you said.

**Comment by pmacMaps** [comment]
@jgravois Here's my first stab at the [first tutorial](https://github.com/pmacMaps/esri-leaflet-doc/blob/master/src/pages/tutorials/create-a-basic-map.md).

I've placed questions in italics.  I'm also just kinda guessing as to what the goal is for these tutorials.

All feedback is greatly appreciated.

**Comment by jgravois** [comment]
awesome! can you submit a PR? that'd make it really easy for me to pull down your work and give feedback.

**Comment by jgravois** [comment]
closing.  thx @pmacMaps!

**Comment by pmacMaps** [comment]
I noticed the tutorial isn't on the website yet.  Will it be pushed with other updates?

**Comment by jgravois** [comment]
its deployed now. 😄
