### ISSUE TITLE
Identifying Features Demo has no data displayed (Dead URL??)

### ISSUE THREAD

**Issue by jmitz** [Esri/esri-leaflet-doc#46]
Troubles on [Identifying Feature](http://esri.github.io/esri-leaflet/examples/identifying-features.html) Demo
It appears the url for the map service (https://tmservices1.esri.com/arcgis/rest/services/LiveFeeds/Earthquakes/MapServer) is no longer available. I went to the [Service link](https://tmservices1.esri.com/arcgis/rest/services/LiveFeeds) and did not see Earthquakes listed. When I checked the "USGS_Seismic_Data" service on that server it shows that the service is scheduled to be retired at the end of the year and is being replaced with an ArcGIS Online [service](https://www.arcgis.com/home/item.html?id=af7568d8579048f7b42e534891824029).
I would have tried to come up with a PR but didn't know what service you might want to use for this example.

**Comment by jgravois** [comment]
thanks for the heads up!

i'm under the impression that some of the latest generation live feed services require users to be signed into the platform, so we'll need to substitute an entirely different map service from [sampleserver6](http://sampleserver6.arcgisonline.com/arcgis/rest/services) sometime very soon.

**Comment by jmitz** [comment]
That was the impression I was getting as well (requiring users to be signed into the platform).
