### ISSUE TITLE
query orderBy documentation clarification

### ISSUE THREAD

**Issue by freewheelCarto** [Esri/esri-leaflet-doc#55]
The documentation could clarify the correct strings for _ascending_ or _descending_ in the second parameter of the orderBy method. 

For example, when I am querying a featureLayer hosted on ArcServer, I can use "descending" and it works.  But if I am querying a featureLayer hosted on AGOL, I found that "desc" works. 

![descending](https://cloud.githubusercontent.com/assets/12546498/17380567/bcdb83a8-5995-11e6-80cd-230f94080547.JPG)

**Comment by jgravois** [comment]
good point.  we'll make sure to call this out soon:

* 'ASC' (ascending) is the default assumed sort order
* 'DESC' (descending) can be passed as an alternative.

Query (FeatureService/Layer) - http://resources.arcgis.com/en/help/arcgis-rest-api/index.html#/Query_Feature_Service_Layer/02r3000000r1000000/
