### ISSUE TITLE
within page section links would be really nice

### ISSUE THREAD

**Issue by jgravois** [Esri/esri-leaflet-doc#6]
example: http://esri.github.io/esri-leaflet/api-reference/controls/geosearch.html

ie: it'd be a real UX improvement if we had links to jump around/share specific sections of pages.

```html
<a herf="#events"><[ResultsEvent]></a>
```

**Comment by jgravois** [comment]
apparently, we already have them, there's just no visual indication of it.

https://esri.github.io/esri-leaflet/api-reference/services/service.html#options

**Comment by pmacMaps** [comment]
A visual indicator that allows a user to copy the link to the section?

Something like this: https://css-tricks.com/zooming-background-images/#article-header-id-0?

**Comment by jgravois** [comment]
exactly.

**Comment by rowanwins** [comment]
Would just a css hover effect suffice on all h3's? Eg slight change of color and perhaps a pointer cursor? If so I'm happy to whack in a pull request

**Comment by rowanwins** [comment]
I also worked out a simple js method to have click events on the headings which change the url hash. 
So I've put in a pull request to address this issue.
