### ISSUE TITLE
create a 'working with feature layers' tutorial

### ISSUE THREAD

**Issue by jgravois** [Esri/esri-leaflet-doc#65]
following the pattern in:
https://github.com/Esri/esri-leaflet-doc/blob/master/src/pages/tutorials/create-your-first-app.md

- [ ] add an `L.esri.featureLayer` to a map
- [ ] clarify that both `MapServer/0` and `FeatureServer/0` layers are both supported
- [ ] remind that services are supported whether you can fetch `f=geojson` or not
- [ ] describe gridded queries
- [ ] define a popup with clientside GeoJSON
- [ ] use renderers plugin to display service symbology

**Comment by pmacMaps** [comment]
Is the plan to create an issue for each tutorial?

I can get started on this, minus bullets 2-4 - they are beyond my knowledge base.

Also, you can add a Map Service as a featureLayer?  If so, I did not know that.

**Comment by jgravois** [comment]
> Is the plan to create an issue for each tutorial?

i'd willing to entertain including any tutorial anyone wants to write, whether there's an open issue for it or not, but i thought i'd start by stubbing out a couple issues for the items we discussed in #44.

> you can add a Map Service as a featureLayer?

not exactly.  you can add an *individual layer* within a map service.  people sometimes assume that only `FeatureServer` layers are supported (see Esri/esri-leaflet#403 for an example).

**Comment by pmacMaps** [comment]
So we would want an example for both a MapServer/0 and a FeatureServer/0?

**Comment by jgravois** [comment]
no.  just some text to explain that they are equivalent.

**Comment by jgravois** [comment]
closed via #72
