### ISSUE TITLE
complete website revamp

### ISSUE THREAD

**Issue by jgravois** [Esri/esri-leaflet-doc#66]
goals:
- responsive
- inline API doc (maybe)
- on fleek (definitely)

**Comment by gavinr** [comment]
:+1: on fleek :100:

**Comment by rowanwins** [comment]
Gday @jgravois 

I'd be happy to provide a bit of assistance on this. 

-  Did you have any thoughts on how you were going to tackle the reponsiveness, eg using some sort of framework etc?
- In terms of the inline API doc do you mean utilising something like jsdoc to generate the docs?
- I've got no idea what this fleek thing is other than what I can vaguely see [in this repo](https://github.com/fleekjs)

The responsive stuff is probably what I'm most comfortable with but I've dabbled a little with jsdoc.

Cheers
Rowan

**Comment by jgravois** [comment]
> @rowanwins Did you have any thoughts on how

i haven't dug into this yet, just logged an issue to remind myself to investigate a website rewrite at some point.

> do you mean utilising something like jsdoc to generate the docs?

yes. thats definitely what i was referring to.

> I've got no idea what this fleek thing is

urbandictionary.com - [on fleek](http://www.urbandictionary.com/define.php?term=on+fleek&defid=8304486#.V8ScueukY7g.twitter)

**Comment by rowanwins** [comment]
> urbandictionary.com - on fleek
We need a Google Translate function for American slang to Australian! In more positive news that reduces the requirements from 3 to 2!

I might make a start on the responsive aspect and will keep you posted.

**Comment by jgravois** [comment]
> I might make a start on the responsive aspect and will keep you posted.

sounds good!

w/ all the head scratching i've done over ozzie/cockney rhyming slang over the years, i'm happy to try and repay the favor.

**Comment by pmacMaps** [comment]
Does the responsive goal relate to how some of the text breaks out of the container and requires horizontal scrolling?  If so, does it also relate to the code samples, or are those okay to scroll?

**Comment by jgravois** [comment]
this is a 'high-level' issue, so the goal relates to any/all sub-optimal behavior on mobile devices.

@gavinr made _serious_ progress on this front in #164, but as for what's left, the former is more irritating than the latter (to me anyway).

**Comment by pmacMaps** [comment]
I may have a lead on getting the tables more mobile friendly.  Unfortunately I don't know the slightest SCSS/SASS, so I can't make the changes.  But I think I may have zeroed in on some of the issues.

The proposed changes would need to be tested, and should only apply below a certain viewport width.
- for the code.nobr elements, change white-space property to "pre-line"
- there are some nobr elements.  If those elements are changed to a span element, it should resolve the breaking text issues
