### ISSUE TITLE
Examples for 1.x Versions

### ISSUE THREAD

**Issue by pmacMaps** [Esri/esri-leaflet-doc#76]
I am still developing applications using the 0.7.x version of Leaflet and 1.x.x version of the Esri plugins.  It appears that the API reference and examples are for 2.x.x versions of the plugins.

Is there a way that the examples and reference can be available for older versions of the plugins?

**Comment by jgravois** [comment]
what exactly has kept you from migrating to Leaflet `1.x`?
despite its release candidate designation, the code has been incredibly stable for quite awhile.

**Comment by pmacMaps** [comment]
I was waiting until it was officially released.  But with this newfound knowledge, I'll start testing porting my existing maps/apps over to the newer versions.

**Comment by jgravois** [comment]
sounds good.  holler if you need a hand.
