### ISSUE TITLE
Document what is available at 1.x.x vs. 2.x.x

### ISSUE THREAD

**Issue by pmacMaps** [Esri/esri-leaflet-doc#77]
Can there be documentation as to what features are available at 2.x.x and 1.x.x?

I was experimenting with `L.esri.find` and got `Uncaught TypeError: L.esri.find is not a function` when using the 1.x.x version.  

It seemed to work at the 2.x.x version.  It would be nice to know ahead of time what works with what version.

**Comment by jgravois** [comment]
it would certainly be nice to publish documentation for both versions, but given my limited bandwidth, i really don't see it happening.

especially since Leaflet's maintainers seem to finally be preparing to pull the trigger on a final `1.0.0` release.
