### ISSUE TITLE
L.esri.dynamicMapLayer Example CORS Issue

### ISSUE THREAD

**Issue by tyleralves** [Esri/esri-leaflet-doc#79]
Dynamic Map Layer example requests a map server that does not have CORS enabled. 
Error: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Tested with this map server and it worked:
https://sampleserver6.arcgisonline.com/arcgis/rest/services/Recreation/MapServer

**Comment by jgravois** [comment]
are you saying that one of our samples utilizes a map service that doesn't support CORS that we fail to account for in code?  if so, which one specifically? 

the service in 'Simple Dynamic Map Layer' is definitely CORS enabled.

**Comment by tyleralves** [comment]
I should have been more specific. The example snippet of code on the API Documentation page for [Dynamic Map Layer](https://esri.github.io/esri-leaflet/api-reference/layers/dynamic-map-layer.html) fails with the error: No 'Access-Control-Allow-Origin' header is present on the requested resource.

When I replace the map server in the example snippet with a different map server, it works.

I believe, but am by no means certain, that this error is due to the map server not being CORS enabled. Regardless of the cause, the code snippet doesn't work.

Should I replace this map server with the map server from the [Simple DynamicMapLayer Example](https://esri.github.io/esri-leaflet/examples/simple-dynamic-map-layer.html)?

**Comment by mostafakhairy** [comment]
i have issue when enabling dynamic map i get COM error  in  10.5 but  its working fine 9.3
 If (Not m_dynamicMap.DynamicMapEnabled) Then
                    m_dynamicMap.DynamicMapEnabled = True
                End If
