### ISSUE TITLE
Stream Plugin Example Server Down

### ISSUE THREAD

**Issue by tyleralves** [Esri/esri-leaflet-doc#80]
Stream server down, temporarily(?)

It's probably temporary because the ArcGIS JS API example uses the same server and is also not working.

Example Here:
https://esri.github.io/esri-leaflet/examples/stream-plugin.html

**Comment by jgravois** [comment]
thanks for pointing out the problem.  i'll try and inform the right folks.  i don't know of another sample server to point at, so there's not much we can do on this side.

**Comment by jgravois** [comment]
looks like the sample is back up now.  they must have got my email.
