### ISSUE TITLE
replace jsdelivr cdn links in samples with unpkg.com links

### ISSUE THREAD

**Issue by jgravois** [Esri/esri-leaflet-doc#82]
i think it'd probably be easiest if we just update all the links in our doc samples to use [unpkg.com](https://unpkg.com).

background info: [jsdelivr/jsdelivr#13136](https://github.com/jsdelivr/jsdelivr/issues/13136)

**Comment by pmacMaps** [comment]
Is this as simple as replacing every instance of the cdn links?  If so, I could probably help with that, once I know what the new links are.

**Comment by jgravois** [comment]
check out https://github.com/Esri/esri-leaflet-doc/pull/89/files.  in our live samples, we'd swap in Leaflet `1.0.0-rc.3` and Esri Leaflet `2.0.2`.  

since [unpkg](https://unpkg.com/#/) serves the [browser bundle](https://github.com/Esri/esri-leaflet/blob/master/package.json#L6) by default, we can even get crafty and chop the url down.
```html
<script src="https://unpkg.com/leaflet@1.0.0-rc.3"></script>
<script src="https://unpkg.com/esri-leaflet@2.0.2"></script>
```
