### ISSUE TITLE
Working with Authenticated Services Tutorial

### ISSUE THREAD

**Issue by pmacMaps** [Esri/esri-leaflet-doc#88]
Create tutorial for http://esri.github.io/esri-leaflet/tutorials/working-with-authenticated-services.html following format of existing tutorials.

@jgravois, feel free to chime in about your goals for this tutorial.

**Comment by jgravois** [comment]
we'll get to this... eventually.

**Comment by pmacMaps** [comment]
@jgravois, I wanted to start this tutorial with a section on ArcGIS Server and submitting a form to add a layer.  The sample map I would be building is at https://gis.ccpa.net/labs/sctf/sctf-leaflet/.

It's based upon the sample page, and includes some error event related stuff.  If you're okay with this direction, I can start working on the tutorial.

**Comment by jgravois** [comment]
that sounds good to me! you can use one of our secure demo services like the one below

http://sampleserver6.arcgisonline.com/arcgis/rest/services/Wildfire_secure_ac2/MapServer
username: user1
password: user1

http://www.arcgis.com/home/webmap/viewer.html?url=http%3A%2F%2Fsampleserver6.arcgisonline.com%2Farcgis%2Frest%2Fservices%2FWildfire_secure_ac2%2FMapServer&source=sd

**Comment by jgravois** [comment]
thanks again @pmacMaps! :tada:
